// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.Collections.ObjectModel;
using UnityEngine;


public partial class Hex : System.ComponentModel.INotifyPropertyChanged {
    
    private Vector2 _arrayCoord;
    
    private Vector2 _cubeCoord;
    
    private Vector3 _worldPos;
    
    private Int32 _height;
    
    private TerrainType _terrainType;
    
    private Int32 _pathParent;
    
    private Int32 _pathScore;
    
    public event PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName){ PropertyChangedEventHandler handler = PropertyChanged; if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName)); }
    public virtual Vector2 arrayCoord {
        get {
            return this._arrayCoord;
        }
        set {
            _arrayCoord = value;
            OnPropertyChanged("arrayCoord");
        }
    }
    
    public virtual Vector2 cubeCoord {
        get {
            return this._cubeCoord;
        }
        set {
            _cubeCoord = value;
            OnPropertyChanged("cubeCoord");
        }
    }
    
    public virtual Vector3 worldPos {
        get {
            return this._worldPos;
        }
        set {
            _worldPos = value;
            OnPropertyChanged("worldPos");
        }
    }
    
    public virtual Int32 height {
        get {
            return this._height;
        }
        set {
            _height = value;
            OnPropertyChanged("height");
        }
    }
    
    public virtual TerrainType terrainType {
        get {
            return this._terrainType;
        }
        set {
            _terrainType = value;
            OnPropertyChanged("terrainType");
        }
    }
    
    public virtual Int32 pathParent {
        get {
            return this._pathParent;
        }
        set {
            _pathParent = value;
            OnPropertyChanged("pathParent");
        }
    }
    
    public virtual Int32 pathScore {
        get {
            return this._pathScore;
        }
        set {
            _pathScore = value;
            OnPropertyChanged("pathScore");
        }
    }
}

public partial class HexProperties : System.ComponentModel.INotifyPropertyChanged {
    
    private Single _side;
    
    private Single _height;
    
    private Single _width;
    
    private Single _tileR;
    
    private Single _tileH;
    
    public event PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName){ PropertyChangedEventHandler handler = PropertyChanged; if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName)); }
    public virtual Single side {
        get {
            return this._side;
        }
        set {
            _side = value;
            OnPropertyChanged("side");
        }
    }
    
    public virtual Single height {
        get {
            return this._height;
        }
        set {
            _height = value;
            OnPropertyChanged("height");
        }
    }
    
    public virtual Single width {
        get {
            return this._width;
        }
        set {
            _width = value;
            OnPropertyChanged("width");
        }
    }
    
    public virtual Single tileR {
        get {
            return this._tileR;
        }
        set {
            _tileR = value;
            OnPropertyChanged("tileR");
        }
    }
    
    public virtual Single tileH {
        get {
            return this._tileH;
        }
        set {
            _tileH = value;
            OnPropertyChanged("tileH");
        }
    }
}

public partial class TerrainSettings : System.ComponentModel.INotifyPropertyChanged {
    
    private Int32 _terrainWidth;
    
    private Int32 _terrainHeight;
    
    private Single _detail;
    
    private Single _altitudeVariation;
    
    public event PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName){ PropertyChangedEventHandler handler = PropertyChanged; if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName)); }
    public virtual Int32 terrainWidth {
        get {
            return this._terrainWidth;
        }
        set {
            _terrainWidth = value;
            OnPropertyChanged("terrainWidth");
        }
    }
    
    public virtual Int32 terrainHeight {
        get {
            return this._terrainHeight;
        }
        set {
            _terrainHeight = value;
            OnPropertyChanged("terrainHeight");
        }
    }
    
    public virtual Single detail {
        get {
            return this._detail;
        }
        set {
            _detail = value;
            OnPropertyChanged("detail");
        }
    }
    
    public virtual Single altitudeVariation {
        get {
            return this._altitudeVariation;
        }
        set {
            _altitudeVariation = value;
            OnPropertyChanged("altitudeVariation");
        }
    }
}
